--------------------------------------------------------
--  파일이 생성됨 - 월요일-3월-23-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ORDERSLOG_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ORDERSLOG_SEQ"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQUENCE1
--------------------------------------------------------

   CREATE SEQUENCE  "SEQUENCE1"  MINVALUE 0 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 0 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table APP_USER
--------------------------------------------------------

  CREATE TABLE "APP_USER" 
   (	"USER_NUM" NUMBER(10,0), 
	"EMAIL" VARCHAR2(256 BYTE), 
	"PW" VARCHAR2(80 BYTE), 
	"TEL" VARCHAR2(20 BYTE), 
	"USERNAME" VARCHAR2(40 BYTE), 
	"GENDER" CHAR(3 BYTE), 
	"ADDRESS" VARCHAR2(150 BYTE), 
	"BIRTH" DATE, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"TYPE" CHAR(1 BYTE), 
	"COL1" VARCHAR2(30 BYTE), 
	"COL2" VARCHAR2(30 BYTE), 
	"COL3" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "APP_USER"."USER_NUM" IS '유저 번호';
   COMMENT ON COLUMN "APP_USER"."EMAIL" IS '메일주소';
   COMMENT ON COLUMN "APP_USER"."PW" IS '비밀번호';
   COMMENT ON COLUMN "APP_USER"."TEL" IS '전화번호';
   COMMENT ON COLUMN "APP_USER"."USERNAME" IS '별명';
   COMMENT ON COLUMN "APP_USER"."GENDER" IS '성별';
   COMMENT ON COLUMN "APP_USER"."ADDRESS" IS '주소';
   COMMENT ON COLUMN "APP_USER"."BIRTH" IS '생년월일';
   COMMENT ON COLUMN "APP_USER"."CREATED_AT" IS '생성일시';
   COMMENT ON COLUMN "APP_USER"."UPDATED_AT" IS '수정일시';
   COMMENT ON COLUMN "APP_USER"."TYPE" IS '유형(학습자/튜터)';
   COMMENT ON COLUMN "APP_USER"."COL1" IS '임시1';
   COMMENT ON COLUMN "APP_USER"."COL2" IS '임시2';
   COMMENT ON COLUMN "APP_USER"."COL3" IS '임시3';
--------------------------------------------------------
--  DDL for Table BOARD_CATEGORY
--------------------------------------------------------

  CREATE TABLE "BOARD_CATEGORY" 
   (	"CATEGORY_NUM" NUMBER(4,0), 
	"NAME" VARCHAR2(128 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "BOARD_CATEGORY"."CATEGORY_NUM" IS '분류번호';
   COMMENT ON COLUMN "BOARD_CATEGORY"."NAME" IS '분류명';
--------------------------------------------------------
--  DDL for Table BOARD_POST
--------------------------------------------------------

  CREATE TABLE "BOARD_POST" 
   (	"POST_NUM" NUMBER(10,0), 
	"CATEFORY_NUM" NUMBER(4,0), 
	"TITLE" VARCHAR2(150 BYTE), 
	"USER_NUM" NUMBER(10,0), 
	"USERNAME" VARCHAR2(30 BYTE), 
	"CREATED_TA" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_TA" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"HIT" NUMBER(5,0) DEFAULT 0, 
	"CONTENT" CLOB, 
	"POST_GROUP" NUMBER(10,0), 
	"POST_STEP" NUMBER(5,0) DEFAULT 0, 
	"INDENT" NUMBER(5,0) DEFAULT 0, 
	"COL1" VARCHAR2(30 BYTE), 
	"COL2" VARCHAR2(30 BYTE), 
	"COL3" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "BOARD_POST"."POST_NUM" IS '게시글번호';
   COMMENT ON COLUMN "BOARD_POST"."CATEFORY_NUM" IS '분류 카테고리';
   COMMENT ON COLUMN "BOARD_POST"."TITLE" IS '제목';
   COMMENT ON COLUMN "BOARD_POST"."USER_NUM" IS '사용자 번호';
   COMMENT ON COLUMN "BOARD_POST"."USERNAME" IS '작성자이름(별칭)';
   COMMENT ON COLUMN "BOARD_POST"."CREATED_TA" IS '작성일';
   COMMENT ON COLUMN "BOARD_POST"."UPDATED_TA" IS '수정일';
   COMMENT ON COLUMN "BOARD_POST"."HIT" IS '조회수';
   COMMENT ON COLUMN "BOARD_POST"."CONTENT" IS '본문내용';
   COMMENT ON COLUMN "BOARD_POST"."POST_GROUP" IS '답글그룹';
   COMMENT ON COLUMN "BOARD_POST"."POST_STEP" IS '답변글의 단계';
   COMMENT ON COLUMN "BOARD_POST"."INDENT" IS '답변글의 들여쓰기';
   COMMENT ON COLUMN "BOARD_POST"."COL1" IS '임시1';
   COMMENT ON COLUMN "BOARD_POST"."COL2" IS '임시2';
   COMMENT ON COLUMN "BOARD_POST"."COL3" IS '임시3';
--------------------------------------------------------
--  DDL for Table CHALLENGE
--------------------------------------------------------

  CREATE TABLE "CHALLENGE" 
   (	"C_NUM" NUMBER(10,0), 
	"CONTENT" CLOB, 
	"TITLE" VARCHAR2(1024 BYTE), 
	"LIMIT_MEMORY" NUMBER(38,0), 
	"LIMIT_TIME" NUMBER(38,0), 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"COL1" VARCHAR2(30 BYTE), 
	"COL2" VARCHAR2(30 BYTE), 
	"USER_NUM" NUMBER(10,0), 
	"PASS_NUM" NUMBER(10,0) DEFAULT 0, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "CHALLENGE"."C_NUM" IS '도전과제 번호';
   COMMENT ON COLUMN "CHALLENGE"."CONTENT" IS '도전과제 내용';
   COMMENT ON COLUMN "CHALLENGE"."TITLE" IS '제목';
   COMMENT ON COLUMN "CHALLENGE"."LIMIT_MEMORY" IS '제한메모리사용량';
   COMMENT ON COLUMN "CHALLENGE"."LIMIT_TIME" IS '제한시간';
   COMMENT ON COLUMN "CHALLENGE"."UPDATED_AT" IS '수정 일시';
   COMMENT ON COLUMN "CHALLENGE"."COL1" IS '임시1';
   COMMENT ON COLUMN "CHALLENGE"."COL2" IS '임시2';
   COMMENT ON COLUMN "CHALLENGE"."USER_NUM" IS '출제자';
   COMMENT ON COLUMN "CHALLENGE"."PASS_NUM" IS '통과한 사람수';
   COMMENT ON COLUMN "CHALLENGE"."CREATED_AT" IS '생성 일시';
--------------------------------------------------------
--  DDL for Table CHALLENGE_CASE
--------------------------------------------------------

  CREATE TABLE "CHALLENGE_CASE" 
   (	"CASE_NUM" NUMBER(10,0), 
	"C_NUM" NUMBER(10,0), 
	"INPUT" CLOB, 
	"OUTPUT" CLOB, 
	"USER_NUM" NUMBER(10,0), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"COL1" VARCHAR2(30 BYTE), 
	"COL2" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("INPUT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("OUTPUT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "CHALLENGE_CASE"."CASE_NUM" IS '케이스번호';
   COMMENT ON COLUMN "CHALLENGE_CASE"."C_NUM" IS '도전문제번호';
   COMMENT ON COLUMN "CHALLENGE_CASE"."INPUT" IS '입력';
   COMMENT ON COLUMN "CHALLENGE_CASE"."OUTPUT" IS '출력(입력에 대응되는 정답';
   COMMENT ON COLUMN "CHALLENGE_CASE"."USER_NUM" IS '답안작성자';
   COMMENT ON COLUMN "CHALLENGE_CASE"."CREATED_AT" IS '생성일시';
   COMMENT ON COLUMN "CHALLENGE_CASE"."UPDATED_AT" IS '수정일시';
   COMMENT ON COLUMN "CHALLENGE_CASE"."COL1" IS '임시1';
   COMMENT ON COLUMN "CHALLENGE_CASE"."COL2" IS '임시2';
--------------------------------------------------------
--  DDL for Table CHALLENGE_RESULT
--------------------------------------------------------

  CREATE TABLE "CHALLENGE_RESULT" 
   (	"RESULT_NUM" NUMBER(10,0), 
	"USER_NUM" NUMBER(10,0), 
	"RESULT_COMMENT" VARCHAR2(1024 BYTE), 
	"STATUS" VARCHAR2(5 BYTE), 
	"CREATED_AT" TIMESTAMP (6), 
	"UPDATED_AT" TIMESTAMP (6), 
	"CODE" CLOB, 
	"C_NUM" NUMBER(10,0), 
	"USED_MEMORY" NUMBER(16,0), 
	"PROCESSING_TIME" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CODE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "CHALLENGE_RESULT"."RESULT_NUM" IS '결과번호';
   COMMENT ON COLUMN "CHALLENGE_RESULT"."USER_NUM" IS '유저 번호';
   COMMENT ON COLUMN "CHALLENGE_RESULT"."RESULT_COMMENT" IS '결과 코멘트';
   COMMENT ON COLUMN "CHALLENGE_RESULT"."STATUS" IS '결과상태';
   COMMENT ON COLUMN "CHALLENGE_RESULT"."CREATED_AT" IS '생성일시';
   COMMENT ON COLUMN "CHALLENGE_RESULT"."UPDATED_AT" IS '수정일시';
   COMMENT ON COLUMN "CHALLENGE_RESULT"."CODE" IS '제출답안';
   COMMENT ON COLUMN "CHALLENGE_RESULT"."C_NUM" IS '도전문제번호';
   COMMENT ON COLUMN "CHALLENGE_RESULT"."USED_MEMORY" IS '사용메모리';
   COMMENT ON COLUMN "CHALLENGE_RESULT"."PROCESSING_TIME" IS '처리시간';
--------------------------------------------------------
--  DDL for Table COMMENT_PREFERENCE
--------------------------------------------------------

  CREATE TABLE "COMMENT_PREFERENCE" 
   (	"PREFERENCE_NUM" NUMBER(10,0), 
	"COMMENT_NUM" NUMBER(10,0), 
	"USER_NUM" VARCHAR2(40 BYTE), 
	"PREFERENCE" CHAR(1 BYTE), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "COMMENT_PREFERENCE"."PREFERENCE_NUM" IS '선호도 번호';
   COMMENT ON COLUMN "COMMENT_PREFERENCE"."COMMENT_NUM" IS '댓글번호';
   COMMENT ON COLUMN "COMMENT_PREFERENCE"."USER_NUM" IS '투표자(회원ID)';
   COMMENT ON COLUMN "COMMENT_PREFERENCE"."PREFERENCE" IS '댓글선호도';
   COMMENT ON COLUMN "COMMENT_PREFERENCE"."CREATED_AT" IS '투표일시';
   COMMENT ON COLUMN "COMMENT_PREFERENCE"."UPDATED_AT" IS '변경일시';
--------------------------------------------------------
--  DDL for Table FNSH_RESULT
--------------------------------------------------------

  CREATE TABLE "FNSH_RESULT" 
   (	"RESULT_NUM" NUMBER(10,0), 
	"TEST_NUM" NUMBER(10,0), 
	"ANSWER" VARCHAR2(1024 BYTE), 
	"STATUS" CHAR(3 BYTE), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"COL1" VARCHAR2(30 BYTE), 
	"COL2" VARCHAR2(30 BYTE), 
	"USER_NUM" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "FNSH_RESULT"."RESULT_NUM" IS '결과번호';
   COMMENT ON COLUMN "FNSH_RESULT"."TEST_NUM" IS '마무리문제 번호';
   COMMENT ON COLUMN "FNSH_RESULT"."ANSWER" IS '제출답안';
   COMMENT ON COLUMN "FNSH_RESULT"."STATUS" IS '정답여부';
   COMMENT ON COLUMN "FNSH_RESULT"."CREATED_AT" IS '생성일시';
   COMMENT ON COLUMN "FNSH_RESULT"."UPDATED_AT" IS '수정일시';
   COMMENT ON COLUMN "FNSH_RESULT"."COL1" IS '임시1';
   COMMENT ON COLUMN "FNSH_RESULT"."COL2" IS '임시2';
   COMMENT ON COLUMN "FNSH_RESULT"."USER_NUM" IS '제출자';
--------------------------------------------------------
--  DDL for Table FNSH_TEST
--------------------------------------------------------

  CREATE TABLE "FNSH_TEST" 
   (	"TEST_NUM" NUMBER(10,0), 
	"UNIT_NUM" NUMBER(10,0), 
	"TITLE" VARCHAR2(256 BYTE), 
	"CONTENT" CLOB, 
	"CORRECT_ANSWER" VARCHAR2(1024 BYTE), 
	"SOLUTION" CLOB, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"COL1" VARCHAR2(30 BYTE), 
	"COL2" VARCHAR2(30 BYTE), 
	"USER_NUM" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("SOLUTION") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "FNSH_TEST"."TEST_NUM" IS '문제번호';
   COMMENT ON COLUMN "FNSH_TEST"."UNIT_NUM" IS '단원번호';
   COMMENT ON COLUMN "FNSH_TEST"."TITLE" IS '문제명';
   COMMENT ON COLUMN "FNSH_TEST"."CONTENT" IS '문제내용';
   COMMENT ON COLUMN "FNSH_TEST"."CORRECT_ANSWER" IS '정답';
   COMMENT ON COLUMN "FNSH_TEST"."SOLUTION" IS '풀이';
   COMMENT ON COLUMN "FNSH_TEST"."CREATED_AT" IS '생성 일시';
   COMMENT ON COLUMN "FNSH_TEST"."UPDATED_AT" IS '수정 일시';
   COMMENT ON COLUMN "FNSH_TEST"."COL1" IS '임시1';
   COMMENT ON COLUMN "FNSH_TEST"."COL2" IS '임시2';
--------------------------------------------------------
--  DDL for Table FNSH_TEST_ANSWER
--------------------------------------------------------

  CREATE TABLE "FNSH_TEST_ANSWER" 
   (	"ANSWER_NUM" NUMBER(10,0), 
	"TEST_NUM" NUMBER(10,0), 
	"CONTENT" VARCHAR2(1024 BYTE), 
	"IS_CORRECT" CHAR(1 BYTE), 
	"CREATED_AT" TIMESTAMP (6), 
	"UPDATED_AT" TIMESTAMP (6), 
	"COL1" VARCHAR2(30 BYTE), 
	"COL2" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "FNSH_TEST_ANSWER"."ANSWER_NUM" IS '답변 번호';
   COMMENT ON COLUMN "FNSH_TEST_ANSWER"."TEST_NUM" IS '문제번호';
   COMMENT ON COLUMN "FNSH_TEST_ANSWER"."CONTENT" IS '선택지 내용';
   COMMENT ON COLUMN "FNSH_TEST_ANSWER"."IS_CORRECT" IS '정답여부';
   COMMENT ON COLUMN "FNSH_TEST_ANSWER"."CREATED_AT" IS '생성 일시';
   COMMENT ON COLUMN "FNSH_TEST_ANSWER"."UPDATED_AT" IS '수정 일시';
   COMMENT ON COLUMN "FNSH_TEST_ANSWER"."COL1" IS '임시1';
   COMMENT ON COLUMN "FNSH_TEST_ANSWER"."COL2" IS '임시2';
--------------------------------------------------------
--  DDL for Table POST_ATTACHMENT
--------------------------------------------------------

  CREATE TABLE "POST_ATTACHMENT" 
   (	"FID" NUMBER(10,0), 
	"POST_NUM" NUMBER(10,0), 
	"FNAME" VARCHAR2(150 BYTE), 
	"FSIZE" VARCHAR2(45 BYTE), 
	"FTYPE" VARCHAR2(50 BYTE), 
	"FDATA" BLOB, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"COL1" VARCHAR2(30 BYTE), 
	"COL2" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("FDATA") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "POST_ATTACHMENT"."FID" IS '파일아이디';
   COMMENT ON COLUMN "POST_ATTACHMENT"."POST_NUM" IS '게시글번호';
   COMMENT ON COLUMN "POST_ATTACHMENT"."FNAME" IS '파일명';
   COMMENT ON COLUMN "POST_ATTACHMENT"."FSIZE" IS '파일크기';
   COMMENT ON COLUMN "POST_ATTACHMENT"."FTYPE" IS '파일유형';
   COMMENT ON COLUMN "POST_ATTACHMENT"."FDATA" IS '첨부파일';
   COMMENT ON COLUMN "POST_ATTACHMENT"."CREATED_AT" IS '작성일';
   COMMENT ON COLUMN "POST_ATTACHMENT"."UPDATED_AT" IS '수정일';
   COMMENT ON COLUMN "POST_ATTACHMENT"."COL1" IS '임시1';
   COMMENT ON COLUMN "POST_ATTACHMENT"."COL2" IS '임시2';
--------------------------------------------------------
--  DDL for Table RBOARD
--------------------------------------------------------

  CREATE TABLE "RBOARD" 
   (	"COMMENT_NUM" NUMBER(10,0), 
	"POST_NUM" NUMBER(10,0), 
	"USER_NUM" VARCHAR2(40 BYTE), 
	"USERNAME" VARCHAR2(30 BYTE), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"CONTENT" CLOB, 
	"COMMENT_GROUP" NUMBER(10,0), 
	"COMMENT_STEP" NUMBER(5,0) DEFAULT 0, 
	"INDENT" NUMBER(5,0) DEFAULT 0, 
	"PRNUM" NUMBER(10,0), 
	"TARGET_USER_NUM" NUMBER(10,0), 
	"TARGET_USERNAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "RBOARD"."COMMENT_NUM" IS '댓글번호';
   COMMENT ON COLUMN "RBOARD"."POST_NUM" IS '게시글번호';
   COMMENT ON COLUMN "RBOARD"."USER_NUM" IS '작성자ID';
   COMMENT ON COLUMN "RBOARD"."USERNAME" IS '작성자이름(별칭)';
   COMMENT ON COLUMN "RBOARD"."CREATED_AT" IS '작성일';
   COMMENT ON COLUMN "RBOARD"."UPDATED_AT" IS '수정일';
   COMMENT ON COLUMN "RBOARD"."CONTENT" IS '본문내용';
   COMMENT ON COLUMN "RBOARD"."COMMENT_GROUP" IS '답글그룹';
   COMMENT ON COLUMN "RBOARD"."COMMENT_STEP" IS '답변글의 단계';
   COMMENT ON COLUMN "RBOARD"."INDENT" IS '답변글의 들여쓰기';
   COMMENT ON COLUMN "RBOARD"."PRNUM" IS '부모댓글번호';
   COMMENT ON COLUMN "RBOARD"."TARGET_USER_NUM" IS '답글대상번호';
   COMMENT ON COLUMN "RBOARD"."TARGET_USERNAME" IS '답글대상이름';
--------------------------------------------------------
--  DDL for Table SUBJECT
--------------------------------------------------------

  CREATE TABLE "SUBJECT" 
   (	"SUBJECT_NUM" NUMBER(10,0), 
	"TITLE" VARCHAR2(256 BYTE), 
	"USER_NUM" NUMBER(10,0), 
	"CREATE_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"COL1" VARCHAR2(30 BYTE), 
	"COL2" VARCHAR2(30 BYTE), 
	"COL3" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "SUBJECT"."SUBJECT_NUM" IS '과목번호';
   COMMENT ON COLUMN "SUBJECT"."TITLE" IS '과목명';
   COMMENT ON COLUMN "SUBJECT"."USER_NUM" IS '출제자';
   COMMENT ON COLUMN "SUBJECT"."CREATE_AT" IS '생성일시';
   COMMENT ON COLUMN "SUBJECT"."UPDATED_AT" IS '수정일시';
   COMMENT ON COLUMN "SUBJECT"."COL1" IS '임시1';
   COMMENT ON COLUMN "SUBJECT"."COL2" IS '임시2';
   COMMENT ON COLUMN "SUBJECT"."COL3" IS '임시3';
--------------------------------------------------------
--  DDL for Table TUTOR_APPLICATION
--------------------------------------------------------

  CREATE TABLE "TUTOR_APPLICATION" 
   (	"APPLICATION_NUM" NUMBER(10,0), 
	"USER_NUM" NUMBER(10,0), 
	"TITLE" VARCHAR2(150 BYTE), 
	"CONTENT" CLOB, 
	"ATTACHMENT" BLOB, 
	"APPROVAL" CHAR(1 BYTE), 
	"CRDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("ATTACHMENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "TUTOR_APPLICATION"."APPLICATION_NUM" IS '신청번호';
   COMMENT ON COLUMN "TUTOR_APPLICATION"."USER_NUM" IS '유저번호';
   COMMENT ON COLUMN "TUTOR_APPLICATION"."TITLE" IS '제목';
   COMMENT ON COLUMN "TUTOR_APPLICATION"."CONTENT" IS '내용';
   COMMENT ON COLUMN "TUTOR_APPLICATION"."ATTACHMENT" IS '첨부파일';
   COMMENT ON COLUMN "TUTOR_APPLICATION"."APPROVAL" IS '승인여부';
   COMMENT ON COLUMN "TUTOR_APPLICATION"."CRDATED_AT" IS '생성일시';
   COMMENT ON COLUMN "TUTOR_APPLICATION"."UPDATED_AT" IS '변경일시';
--------------------------------------------------------
--  DDL for Table UNIT
--------------------------------------------------------

  CREATE TABLE "UNIT" 
   (	"UNIT_NUM" NUMBER(10,0), 
	"SUBJECT_NUM" NUMBER(10,0), 
	"CONTENT" CLOB, 
	"TITLE" VARCHAR2(256 BYTE), 
	"CHAPTER_DEPTH" NVARCHAR2(50), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"COL1" VARCHAR2(30 BYTE), 
	"COL2" VARCHAR2(30 BYTE), 
	"COL3" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "UNIT"."UNIT_NUM" IS '단원번호';
   COMMENT ON COLUMN "UNIT"."SUBJECT_NUM" IS '과목번호';
   COMMENT ON COLUMN "UNIT"."CONTENT" IS '내용(HTML)';
   COMMENT ON COLUMN "UNIT"."TITLE" IS '단원제목';
   COMMENT ON COLUMN "UNIT"."CHAPTER_DEPTH" IS '과목 내 챕터 번호';
   COMMENT ON COLUMN "UNIT"."CREATED_AT" IS '생성일시';
   COMMENT ON COLUMN "UNIT"."UPDATED_AT" IS '수정일시';
   COMMENT ON COLUMN "UNIT"."COL1" IS '임시1';
   COMMENT ON COLUMN "UNIT"."COL2" IS '임시2';
   COMMENT ON COLUMN "UNIT"."COL3" IS '임시3';
--------------------------------------------------------
--  DDL for Table UNIT_COMPLETION
--------------------------------------------------------

  CREATE TABLE "UNIT_COMPLETION" 
   (	"COM_NUM" NUMBER(10,0), 
	"USER_NUM" NUMBER(10,0), 
	"UNIT_NUM" NUMBER(10,0), 
	"STATUS" CHAR(1 BYTE), 
	"CREATED_AT" TIMESTAMP (6), 
	"UPDATED_AT" TIMESTAMP (6), 
	"COL1" VARCHAR2(30 BYTE), 
	"COL2" VARCHAR2(30 BYTE), 
	"COL3" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "UNIT_COMPLETION"."COM_NUM" IS '완료번호';
   COMMENT ON COLUMN "UNIT_COMPLETION"."USER_NUM" IS '유저번호';
   COMMENT ON COLUMN "UNIT_COMPLETION"."UNIT_NUM" IS '과목번호';
   COMMENT ON COLUMN "UNIT_COMPLETION"."STATUS" IS '완료상태';
   COMMENT ON COLUMN "UNIT_COMPLETION"."CREATED_AT" IS '생성일시';
   COMMENT ON COLUMN "UNIT_COMPLETION"."UPDATED_AT" IS '수정일시';
   COMMENT ON COLUMN "UNIT_COMPLETION"."COL1" IS '임시1';
   COMMENT ON COLUMN "UNIT_COMPLETION"."COL2" IS '임시2';
   COMMENT ON COLUMN "UNIT_COMPLETION"."COL3" IS '임시3';
--------------------------------------------------------
--  DDL for Index CHALLENGE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHALLENGE_PK" ON "CHALLENGE" ("C_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TUTOR_APPLICATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TUTOR_APPLICATION_PK" ON "TUTOR_APPLICATION" ("APPLICATION_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FNSH_TEST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FNSH_TEST_PK" ON "FNSH_TEST" ("TEST_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TABLE1_PK" ON "CHALLENGE_CASE" ("CASE_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CHALLENGE_RESULT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHALLENGE_RESULT_PK" ON "CHALLENGE_RESULT" ("RESULT_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SUBJECT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUBJECT_PK" ON "SUBJECT" ("SUBJECT_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FNSH_TEST_ANSWER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FNSH_TEST_ANSWER_PK" ON "FNSH_TEST_ANSWER" ("ANSWER_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UNIT_COMPLETION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UNIT_COMPLETION_PK" ON "UNIT_COMPLETION" ("COM_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PST_ATTACHMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PST_ATTACHMENT_PK" ON "POST_ATTACHMENT" ("FID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BOARD_CATEGORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOARD_CATEGORY_PK" ON "BOARD_CATEGORY" ("CATEGORY_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BOARD_POST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOARD_POST_PK" ON "BOARD_POST" ("POST_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FNSH_RESULT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FNSH_RESULT_PK" ON "FNSH_RESULT" ("RESULT_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UNIT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UNIT_PK" ON "UNIT" ("UNIT_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index APP_USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APP_USER_PK" ON "APP_USER" ("USER_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BOARD_CATEGORY_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOARD_CATEGORY_UK1" ON "BOARD_CATEGORY" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COMMENT_PREFERENCE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "COMMENT_PREFERENCE_PK" ON "COMMENT_PREFERENCE" ("PREFERENCE_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RBOARD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RBOARD_PK" ON "RBOARD" ("COMMENT_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Procedure BOOKINSERTORUPDATE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "BOOKINSERTORUPDATE" (
  p_bookid IN Book.bookid%TYPE,
  p_bookname IN Book.bookname%TYPE,
  p_publisher IN Book.publisher%TYPE,
  p_price   IN Book.price%TYPE,
  r_errcode OUT NUMBER,
  r_errmsg OUT VARCHAR2
)
AS 
l_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO l_count 
  FROM Book 
  WHERE bookname = p_bookname
    AND publisher = p_publisher;
  IF l_count != 0 THEN
    UPDATE Book SET price = p_price
    WHERE bookname = p_bookname
    AND publisher = p_publisher;
  ELSE 
    INSERT INTO Book(bookid, bookname, publisher, price)
    VALUES (p_bookid, p_bookname, p_publisher, p_price);
  END IF;
EXCEPTION 
  WHEN OTHERS THEN
    ROLLBACK;
    r_errcode := SQLCODE;
    r_errmsg := SQLERRM;
    DBMS_OUTPUT.PUT_LINE('ERROR:'||SQLCODE||'-'||SQLERRM);
END;



/
--------------------------------------------------------
--  DDL for Function GRADE
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "GRADE" (
  p_custid Customer.custid%TYPE
) RETURN VARCHAR2
IS 
l_grade VARCHAR(6);
l_sum NUMBER;
BEGIN
  SELECT SUM(saleprice)  INTO l_sum
    FROM Orders 
    where custid = p_custid;
  IF l_sum >=100 THEN
    l_grade := '우수';
  ELSE 
    l_grade := '일반';
  END IF;
  RETURN l_grade;
END;



/
--------------------------------------------------------
--  Constraints for Table FNSH_TEST_ANSWER
--------------------------------------------------------

  ALTER TABLE "FNSH_TEST_ANSWER" ADD CONSTRAINT "FNSH_TEST_ANSWER_PK" PRIMARY KEY ("ANSWER_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FNSH_TEST_ANSWER" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "FNSH_TEST_ANSWER" MODIFY ("TEST_NUM" NOT NULL ENABLE);
  ALTER TABLE "FNSH_TEST_ANSWER" MODIFY ("ANSWER_NUM" NOT NULL ENABLE);
  ALTER TABLE "FNSH_TEST_ANSWER" MODIFY ("COL2" NOT NULL ENABLE);
  ALTER TABLE "FNSH_TEST_ANSWER" MODIFY ("COL1" NOT NULL ENABLE);
  ALTER TABLE "FNSH_TEST_ANSWER" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "FNSH_TEST_ANSWER" MODIFY ("IS_CORRECT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CHALLENGE
--------------------------------------------------------

  ALTER TABLE "CHALLENGE" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "CHALLENGE" MODIFY ("USER_NUM" NOT NULL ENABLE);
  ALTER TABLE "CHALLENGE" ADD CONSTRAINT "CHALLENGE_PK" PRIMARY KEY ("C_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CHALLENGE" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "CHALLENGE" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "CHALLENGE" MODIFY ("C_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOARD_POST
--------------------------------------------------------

  ALTER TABLE "BOARD_POST" ADD CONSTRAINT "BOARD_POST_PK" PRIMARY KEY ("POST_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BOARD_POST" MODIFY ("POST_NUM" NOT NULL ENABLE);
  ALTER TABLE "BOARD_POST" MODIFY ("COL3" NOT NULL ENABLE);
  ALTER TABLE "BOARD_POST" MODIFY ("COL2" NOT NULL ENABLE);
  ALTER TABLE "BOARD_POST" MODIFY ("COL1" NOT NULL ENABLE);
  ALTER TABLE "BOARD_POST" MODIFY ("UPDATED_TA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table UNIT
--------------------------------------------------------

  ALTER TABLE "UNIT" ADD CONSTRAINT "UNIT_PK" PRIMARY KEY ("UNIT_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "UNIT" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "UNIT" MODIFY ("CHAPTER_DEPTH" NOT NULL ENABLE);
  ALTER TABLE "UNIT" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "UNIT" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "UNIT" MODIFY ("SUBJECT_NUM" NOT NULL ENABLE);
  ALTER TABLE "UNIT" MODIFY ("UNIT_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FNSH_RESULT
--------------------------------------------------------

  ALTER TABLE "FNSH_RESULT" MODIFY ("USER_NUM" NOT NULL ENABLE);
  ALTER TABLE "FNSH_RESULT" ADD CONSTRAINT "FNSH_RESULT_PK" PRIMARY KEY ("RESULT_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FNSH_RESULT" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "FNSH_RESULT" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "FNSH_RESULT" MODIFY ("ANSWER" NOT NULL ENABLE);
  ALTER TABLE "FNSH_RESULT" MODIFY ("TEST_NUM" NOT NULL ENABLE);
  ALTER TABLE "FNSH_RESULT" MODIFY ("RESULT_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMENT_PREFERENCE
--------------------------------------------------------

  ALTER TABLE "COMMENT_PREFERENCE" ADD CONSTRAINT "COMMENT_PREFERENCE_PK" PRIMARY KEY ("PREFERENCE_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "COMMENT_PREFERENCE" MODIFY ("UPDATED_AT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOARD_CATEGORY
--------------------------------------------------------

  ALTER TABLE "BOARD_CATEGORY" ADD CONSTRAINT "BOARD_CATEGORY_UK1" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BOARD_CATEGORY" ADD CONSTRAINT "BOARD_CATEGORY_PK" PRIMARY KEY ("CATEGORY_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FNSH_TEST
--------------------------------------------------------

  ALTER TABLE "FNSH_TEST" MODIFY ("COL2" NOT NULL ENABLE);
  ALTER TABLE "FNSH_TEST" MODIFY ("COL1" NOT NULL ENABLE);
  ALTER TABLE "FNSH_TEST" MODIFY ("USER_NUM" NOT NULL ENABLE);
  ALTER TABLE "FNSH_TEST" ADD CONSTRAINT "FNSH_TEST_PK" PRIMARY KEY ("TEST_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FNSH_TEST" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "FNSH_TEST" MODIFY ("CORRECT_ANSWER" NOT NULL ENABLE);
  ALTER TABLE "FNSH_TEST" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "FNSH_TEST" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "FNSH_TEST" MODIFY ("UNIT_NUM" NOT NULL ENABLE);
  ALTER TABLE "FNSH_TEST" MODIFY ("TEST_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table APP_USER
--------------------------------------------------------

  ALTER TABLE "APP_USER" ADD CONSTRAINT "APP_USER_PK" PRIMARY KEY ("USER_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "APP_USER" MODIFY ("UPDATED_AT" NOT NULL ENABLE);
  ALTER TABLE "APP_USER" MODIFY ("BIRTH" NOT NULL ENABLE);
  ALTER TABLE "APP_USER" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "APP_USER" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "APP_USER" MODIFY ("TEL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POST_ATTACHMENT
--------------------------------------------------------

  ALTER TABLE "POST_ATTACHMENT" ADD CONSTRAINT "PST_ATTACHMENT_PK" PRIMARY KEY ("FID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "POST_ATTACHMENT" MODIFY ("COL2" NOT NULL ENABLE);
  ALTER TABLE "POST_ATTACHMENT" MODIFY ("COL1" NOT NULL ENABLE);
  ALTER TABLE "POST_ATTACHMENT" MODIFY ("UPDATED_AT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CHALLENGE_RESULT
--------------------------------------------------------

  ALTER TABLE "CHALLENGE_RESULT" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "CHALLENGE_RESULT" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "CHALLENGE_RESULT" MODIFY ("USER_NUM" NOT NULL ENABLE);
  ALTER TABLE "CHALLENGE_RESULT" MODIFY ("RESULT_NUM" NOT NULL ENABLE);
  ALTER TABLE "CHALLENGE_RESULT" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "CHALLENGE_RESULT" MODIFY ("C_NUM" NOT NULL ENABLE);
  ALTER TABLE "CHALLENGE_RESULT" ADD CONSTRAINT "CHALLENGE_RESULT_PK" PRIMARY KEY ("RESULT_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CHALLENGE_RESULT" MODIFY ("USED_MEMORY" NOT NULL ENABLE);
  ALTER TABLE "CHALLENGE_RESULT" MODIFY ("PROCESSING_TIME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TUTOR_APPLICATION
--------------------------------------------------------

  ALTER TABLE "TUTOR_APPLICATION" ADD CONSTRAINT "TUTOR_APPLICATION_PK" PRIMARY KEY ("APPLICATION_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TUTOR_APPLICATION" MODIFY ("UPDATED_AT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RBOARD
--------------------------------------------------------

  ALTER TABLE "RBOARD" ADD CONSTRAINT "RBOARD_PK" PRIMARY KEY ("COMMENT_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "RBOARD" MODIFY ("TARGET_USERNAME" NOT NULL ENABLE);
  ALTER TABLE "RBOARD" MODIFY ("TARGET_USER_NUM" NOT NULL ENABLE);
  ALTER TABLE "RBOARD" MODIFY ("PRNUM" NOT NULL ENABLE);
  ALTER TABLE "RBOARD" MODIFY ("UPDATED_AT" NOT NULL ENABLE);
  ALTER TABLE "RBOARD" MODIFY ("COMMENT_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CHALLENGE_CASE
--------------------------------------------------------

  ALTER TABLE "CHALLENGE_CASE" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("CASE_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CHALLENGE_CASE" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "CHALLENGE_CASE" MODIFY ("USER_NUM" NOT NULL ENABLE);
  ALTER TABLE "CHALLENGE_CASE" MODIFY ("OUTPUT" NOT NULL ENABLE);
  ALTER TABLE "CHALLENGE_CASE" MODIFY ("INPUT" NOT NULL ENABLE);
  ALTER TABLE "CHALLENGE_CASE" MODIFY ("C_NUM" NOT NULL ENABLE);
  ALTER TABLE "CHALLENGE_CASE" MODIFY ("CASE_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SUBJECT
--------------------------------------------------------

  ALTER TABLE "SUBJECT" ADD CONSTRAINT "SUBJECT_PK" PRIMARY KEY ("SUBJECT_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SUBJECT" MODIFY ("CREATE_AT" NOT NULL ENABLE);
  ALTER TABLE "SUBJECT" MODIFY ("USER_NUM" NOT NULL ENABLE);
  ALTER TABLE "SUBJECT" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "SUBJECT" MODIFY ("SUBJECT_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table UNIT_COMPLETION
--------------------------------------------------------

  ALTER TABLE "UNIT_COMPLETION" ADD CONSTRAINT "UNIT_COMPLETION_PK" PRIMARY KEY ("COM_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "UNIT_COMPLETION" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "UNIT_COMPLETION" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "UNIT_COMPLETION" MODIFY ("UNIT_NUM" NOT NULL ENABLE);
  ALTER TABLE "UNIT_COMPLETION" MODIFY ("USER_NUM" NOT NULL ENABLE);
  ALTER TABLE "UNIT_COMPLETION" MODIFY ("COM_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BOARD_POST
--------------------------------------------------------

  ALTER TABLE "BOARD_POST" ADD CONSTRAINT "BOARD_POST_FK1" FOREIGN KEY ("POST_NUM")
	  REFERENCES "BOARD_CATEGORY" ("CATEGORY_NUM") ENABLE;
  ALTER TABLE "BOARD_POST" ADD CONSTRAINT "BOARD_POST_FK2" FOREIGN KEY ("USER_NUM")
	  REFERENCES "APP_USER" ("USER_NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CHALLENGE
--------------------------------------------------------

  ALTER TABLE "CHALLENGE" ADD CONSTRAINT "CHALLENGE_FK1" FOREIGN KEY ("USER_NUM")
	  REFERENCES "APP_USER" ("USER_NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CHALLENGE_CASE
--------------------------------------------------------

  ALTER TABLE "CHALLENGE_CASE" ADD CONSTRAINT "CHALLENGE_CASE_FK1" FOREIGN KEY ("C_NUM")
	  REFERENCES "CHALLENGE" ("C_NUM") ENABLE;
  ALTER TABLE "CHALLENGE_CASE" ADD CONSTRAINT "CHALLENGE_CASE_FK2" FOREIGN KEY ("USER_NUM")
	  REFERENCES "APP_USER" ("USER_NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CHALLENGE_RESULT
--------------------------------------------------------

  ALTER TABLE "CHALLENGE_RESULT" ADD CONSTRAINT "CHALLENGE_RESULT_FK1" FOREIGN KEY ("C_NUM")
	  REFERENCES "CHALLENGE" ("C_NUM") ENABLE;
  ALTER TABLE "CHALLENGE_RESULT" ADD CONSTRAINT "CHALLENGE_RESULT_FK2" FOREIGN KEY ("USER_NUM")
	  REFERENCES "APP_USER" ("USER_NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMENT_PREFERENCE
--------------------------------------------------------

  ALTER TABLE "COMMENT_PREFERENCE" ADD CONSTRAINT "COMMENT_PREFERENCE_FK1" FOREIGN KEY ("PREFERENCE_NUM")
	  REFERENCES "COMMENT_PREFERENCE" ("PREFERENCE_NUM") ENABLE;
  ALTER TABLE "COMMENT_PREFERENCE" ADD CONSTRAINT "COMMENT_PREFERENCE_FK2" FOREIGN KEY ("PREFERENCE_NUM")
	  REFERENCES "APP_USER" ("USER_NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FNSH_RESULT
--------------------------------------------------------

  ALTER TABLE "FNSH_RESULT" ADD CONSTRAINT "FNSH_RESULT_FK1" FOREIGN KEY ("TEST_NUM")
	  REFERENCES "FNSH_TEST" ("TEST_NUM") ENABLE;
  ALTER TABLE "FNSH_RESULT" ADD CONSTRAINT "FNSH_RESULT_FK2" FOREIGN KEY ("USER_NUM")
	  REFERENCES "APP_USER" ("USER_NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FNSH_TEST
--------------------------------------------------------

  ALTER TABLE "FNSH_TEST" ADD CONSTRAINT "FNSH_TEST_FK1" FOREIGN KEY ("UNIT_NUM")
	  REFERENCES "UNIT" ("UNIT_NUM") ENABLE;
  ALTER TABLE "FNSH_TEST" ADD CONSTRAINT "FNSH_TEST_FK2" FOREIGN KEY ("USER_NUM")
	  REFERENCES "APP_USER" ("USER_NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FNSH_TEST_ANSWER
--------------------------------------------------------

  ALTER TABLE "FNSH_TEST_ANSWER" ADD CONSTRAINT "FNSH_TEST_ANSWER_FK1" FOREIGN KEY ("TEST_NUM")
	  REFERENCES "FNSH_TEST" ("TEST_NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POST_ATTACHMENT
--------------------------------------------------------

  ALTER TABLE "POST_ATTACHMENT" ADD CONSTRAINT "POST_ATTACHMENT_FK1" FOREIGN KEY ("POST_NUM")
	  REFERENCES "BOARD_POST" ("POST_NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RBOARD
--------------------------------------------------------

  ALTER TABLE "RBOARD" ADD CONSTRAINT "RBOARD_FK1" FOREIGN KEY ("POST_NUM")
	  REFERENCES "BOARD_POST" ("POST_NUM") ENABLE;
  ALTER TABLE "RBOARD" ADD CONSTRAINT "RBOARD_FK2" FOREIGN KEY ("COMMENT_NUM")
	  REFERENCES "APP_USER" ("USER_NUM") ENABLE;
  ALTER TABLE "RBOARD" ADD CONSTRAINT "RBOARD_FK3" FOREIGN KEY ("COMMENT_NUM")
	  REFERENCES "RBOARD" ("COMMENT_NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SUBJECT
--------------------------------------------------------

  ALTER TABLE "SUBJECT" ADD CONSTRAINT "SUBJECT_FK1" FOREIGN KEY ("USER_NUM")
	  REFERENCES "APP_USER" ("USER_NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TUTOR_APPLICATION
--------------------------------------------------------

  ALTER TABLE "TUTOR_APPLICATION" ADD CONSTRAINT "TUTOR_APPLICATION_FK1" FOREIGN KEY ("USER_NUM")
	  REFERENCES "APP_USER" ("USER_NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table UNIT
--------------------------------------------------------

  ALTER TABLE "UNIT" ADD CONSTRAINT "UNIT_FK1" FOREIGN KEY ("SUBJECT_NUM")
	  REFERENCES "SUBJECT" ("SUBJECT_NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table UNIT_COMPLETION
--------------------------------------------------------

  ALTER TABLE "UNIT_COMPLETION" ADD CONSTRAINT "UNIT_COMPLETION_FK1" FOREIGN KEY ("UNIT_NUM")
	  REFERENCES "UNIT" ("UNIT_NUM") ENABLE;
  ALTER TABLE "UNIT_COMPLETION" ADD CONSTRAINT "UNIT_COMPLETION_FK2" FOREIGN KEY ("USER_NUM")
	  REFERENCES "APP_USER" ("USER_NUM") ENABLE;
